name: Deploy services
on:
  push:
    branches:
      - main
    paths:
      - apps/**
inputs:
  node-version:
    description: 'Node.js version'
    default: '20'
    required: false
  pnpm-version:
    description: 'pnpm version'
    default: '9'
    required: false
jobs:
  get-changes:
    runs-on: ubuntu-latest
    needs: setup
    env:
      WORKERS_FOLDER: apps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: export changed workers
        id: export-changed-workers
        run: |
          pnpm install
          FOLDERS=$(pnpm run get_changes --silent)
          echo "services=$FOLDERS" >> $GITHUB_OUTPUT
      - run: echo ${{ fromJSON(steps.export-changed-workers.outputs.services) }}
    outputs:
      services: ${{ steps.export-changed-workers.outputs.services }}
  deploy-services:
    runs-on: ubuntu-latest
    needs: [setup, get-changes]
    strategy:
      matrix:
        folders: ${{ fromJSON(needs.get-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v4
      - name: deployservices
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.14.0'
          workingDirectory: ${{ matrix.folders }}
