name: Deploy services
on:
  push:
    branches:
      - dev
    paths:
      - apps/**
jobs:
  get-changes:
    runs-on: ubuntu-latest
    env:
      WORKERS_FOLDER: apps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: export changed workers
        id: export-changed-workers
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          FOLDERS=$(pnpm run get_changes --silent)
          echo "services=$FOLDERS" >> $GITHUB_OUTPUT
      - run: echo ${{ fromJSON(steps.export-changed-workers.outputs.services) }}
    outputs:
      services: ${{ steps.export-changed-workers.outputs.services }}
  deploy-services:
    runs-on: ubuntu-latest
    needs: get-changes
    strategy:
      matrix: 
        folders: ${{ fromJSON(needs.get-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v4
      - name: deployservices
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.14.0'
          workingDirectory: ${{ matrix.folders }}
