name: Deploy

on:
  workflow_dispatch:
    inputs:
      workerName:
        description: 'Name of the worker to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.14.0'
          workingDirectory: apps/${{ github.event.inputs.workerName }}
