name: Deploy services
on:
  push:
    branches:
      - dev
    paths:
      - apps/**
env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'
jobs:
  get-changes:
    runs-on: ubuntu-latest
    env:
      WORKERS_FOLDER: apps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: export changed workers
        id: export-changed-workers
        run: |
          pnpm install
          FOLDERS=$(pnpm run get_changes --silent)
          echo "services=$FOLDERS" >> $GITHUB_OUTPUT
      - run: echo ${{ fromJSON(steps.export-changed-workers.outputs.services) }}
    outputs:
      services: ${{ steps.export-changed-workers.outputs.services }}
  deploy-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders: ${{ fromJSON(needs.get-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v4
      - name: deployservices
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.14.0'
          workingDirectory: ${{ matrix.folders }}
